- hosts: localhost
  tasks:
  - name: "sync website"
    synchronize:
      src: templates/
      dest: /var/www/{{ domain }}
      archive: no
      checksum: yes
      recursive: yes
      delete: yes
    become: no
